seed: 36

dataset: LFW
criterion: VGG
embedding_type: dino

max_images_to_use: 500

lambda_global_cls: 10
lambda_global_ssim: 1
lambda_global_identity: 5
lambda_VGG: 1
lambda_l1: 0
lambda_l2: 0

content_reg_dino: 0.001
content_reg_vgg: 0.0001

dino_model_name: dino_vits8
dino_global_patch_size: 224
upsample_mode: bilinear # ['nearest', 'bilinear']

content_dim: 128
class_dim: 256
n_adain_layers: 4
adain_dim: 256

lr_generator: 0.003
lr_latent_codes: 0.0003

min_lr: 0.00001
epochs: 100
noise_std: 1
batch_size: 16

swap_gen: 0
warm_up_epochs: 20