seed: 42

dataset: MNIST
criterion: Naive
generator: Basic

lambda_global_cls: 10.0
lambda_global_ssim: 1.0
lambda_global_identity: 1.0
lambda_l2: 1.0
content_embedding_reg: 0.001

dino_model_name: dino_vits8
dino_global_patch_size: 224
upsample_mode: bilinear # ['nearest', 'bilinear']

lr: 0.001
epochs: 10
noise_std: 0.3
batch_size: 64
